### ISSUE TITLE
Appending a slash to URL

### ISSUE THREAD

**Issue by bluecube** [NCMI/jsonrpc#5]
Hi, I'm trying to use jsonrpc with and found a problem -- a slash is always added to the url used for http requests in JSONRPCProxy. The modified url then doesn't work (in my case with xbmc).  This happens both with JSONRPCProxy.from_url() and with JSONRPCProxy constructor and is caused by the line result.append('') in JSONRPCProxy._get_url() . Removing the line seems like an easy fix, but your tests seem to indicate that this behavior is a wanted feature, so I didn't make a pull request with that yet.

**Comment by fiddlerwoaroof** [comment]
I fixed this, the tests in question were written without much thought.
